name: build-web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Enable web
        run: flutter config --enable-web
      - name: Fetch deps
        run: flutter pub get
        working-directory: frontend
      - name: Build web
        run: flutter build web --release --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }}
        working-directory: frontend
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spaced-web
          path: frontend/build/web
